# Nix workflow
# https://docs.github.com/en/actions/writing-workflows

name: Nix

on:
  push:
    branches:
      - main
      - v2
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  pull_request:
    branches:
      - main
      - v2

concurrency:
  group: nix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix:
    name: Build & Check
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Check flake
        run: nix flake check

      - name: Build package
        run: make build-nix

      - name: Publish rolling release to FlakeHub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        # https://github.com/DeterminateSystems/flakehub-push
        uses: DeterminateSystems/flakehub-push@9f22a225279b7dc785553ff476bad4f0cb4e764b # main
        with:
          name: stolasapp/erato
          rolling: true
          visibility: unlisted
          include-output-paths: true

      - name: Publish tagged release to FlakeHub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        # https://github.com/DeterminateSystems/flakehub-push
        uses: DeterminateSystems/flakehub-push@9f22a225279b7dc785553ff476bad4f0cb4e764b # main
        with:
          name: stolasapp/erato
          visibility: unlisted
          include-output-paths: true
